### ISSUE TITLE
Where to print

### ISSUE THREAD

**Issue by rmeertens** [ResEnv/SensorTape#2]
Hey guys,

Just found your work, awesome stuff. You mentioned you found somebody on alibaba. Can I have a link to the supplier?

**Comment by jonnycowboy** [comment]
Also interested in an answer to this especially in a high temperature flexible tape (ex DuPont Pyralux HT).

**Comment by adementyev** [comment]
For assembly/manufacturing we used a contract manufacturer company: http://aqs-inc.com/
We sourced parts and supplies from this company http://www.hkkzd.com/
Recently, places such PCB pool https://www.pcb-pool.com/ppus/order_productconfiguration_js.html
started offering flex circuits. This is a lot more convenient for prototyping.

**Comment by rmeertens** [comment]
Awesome. Thank you very much for your reply!
